Fix errors that can occur with partial data
TypeError: 'NoneType' object is not callable
TypeError: 'DataFrame' object is not callable

So since the data[1:] is somehow callable in the working case (since we are using @property in the accessor it requires a callable object to be returned), we must use a 0 argument lambda to return the data.  I am not sure if there is a better solution and this is just a workaround or if its the ideal method to solve it.  Regardless tested and working.

Also try in current version:
tick = yf.Ticker('ABMD')
tick.cashflow()

It will crash since it returns only the description column, and no data but there is still a table.

tick = yf.Ticker('VTI')
tick.cashflow()

will test the case for an ETF which has no table and gives ValueError.  These are 2 very common and easy to reproduce error scenarios.

Sorry to not have had this working in the original PR.